version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
grpc:
    listen: 'tcp://127.0.0.1:9001'
    proto:
        - app/proto/service.proto
server:
    command: 'php app.php'
    relay: pipes
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
metrics:
    address: '127.0.0.1:2112'
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: app/public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        debug: true
        supervisor:
            max_worker_memory: 100
