version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
grpc:
    listen: 'tcp://127.0.0.1:9001'
    proto:
        - first.proto
        - second.proto
server:
    command: 'php app.php'
    relay: pipes
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
metrics:
    address: '127.0.0.1:2112'
